name: Hospital App CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Java for Android builds
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11

    # Set up Android SDK
    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 33
        build-tools: 33.0.0

    # Install dependencies
    - name: Install dependencies
      run: ./gradlew dependencies

    # Build the app
    - name: Build the app
      run: ./gradlew assembleDebug

    # Run lint checks
    - name: Run Lint
      run: ./gradlew lint

    # Run tests
    - name: Run Unit Tests
      run: ./gradlew test

  deploy:
    name: Deploy to Firebase Hosting
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Firebase CLI
    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    # Authenticate Firebase
    - name: Authenticate Firebase
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_AUTH_TOKEN }}
      run: firebase login:ci --no-localhost

    # Deploy to Firebase Hosting
    - name: Deploy to Firebase Hosting
      run: firebase deploy --only hosting
